var annotated_dup =
[
    [ "CardHouse", "namespaceCardHouse.html", [
      [ "SampleGames", "namespaceCardHouse_1_1SampleGames.html", [
        [ "DeckBuilder", "namespaceCardHouse_1_1SampleGames_1_1DeckBuilder.html", [
          [ "DamageGroupOperator", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageGroupOperator.html", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageGroupOperator" ],
          [ "DamageTargetOperator", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageTargetOperator.html", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageTargetOperator" ],
          [ "Health", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1Health.html", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1Health" ]
        ] ],
        [ "MemoryMatch", "namespaceCardHouse_1_1SampleGames_1_1MemoryMatch.html", [
          [ "MemoryCard", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryCard.html", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryCard" ],
          [ "MemoryGame", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryGame.html", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryGame" ],
          [ "MemoryUI", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryUI.html", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryUI" ]
        ] ],
        [ "Solitaire", "namespaceCardHouse_1_1SampleGames_1_1Solitaire.html", [
          [ "SolitaireCardDragHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireCardDragHandler.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireCardDragHandler" ],
          [ "SolitaireColumnChangeHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnChangeHandler.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnChangeHandler" ],
          [ "SolitaireColumnDropGate", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnDropGate.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnDropGate" ],
          [ "SolitaireDeckClickHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireDeckClickHandler.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireDeckClickHandler" ],
          [ "SolitaireScorePileDropGate", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireScorePileDropGate.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireScorePileDropGate" ],
          [ "SolitaireSetup", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireSetup.html", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireSetup" ]
        ] ],
        [ "Tarot", "namespaceCardHouse_1_1SampleGames_1_1Tarot.html", [
          [ "SpreadManager", "classCardHouse_1_1SampleGames_1_1Tarot_1_1SpreadManager.html", "classCardHouse_1_1SampleGames_1_1Tarot_1_1SpreadManager" ],
          [ "TarotSpread", "classCardHouse_1_1SampleGames_1_1Tarot_1_1TarotSpread.html", "classCardHouse_1_1SampleGames_1_1Tarot_1_1TarotSpread" ]
        ] ]
      ] ],
      [ "TestScenes", "namespaceCardHouse_1_1TestScenes.html", [
        [ "WaypointTesterCard", "classCardHouse_1_1TestScenes_1_1WaypointTesterCard.html", "classCardHouse_1_1TestScenes_1_1WaypointTesterCard" ],
        [ "WaypointTesterGroup", "classCardHouse_1_1TestScenes_1_1WaypointTesterGroup.html", "classCardHouse_1_1TestScenes_1_1WaypointTesterGroup" ]
      ] ],
      [ "Tutorial", "namespaceCardHouse_1_1Tutorial.html", [
        [ "LaunchDataScriptable", "classCardHouse_1_1Tutorial_1_1LaunchDataScriptable.html", "classCardHouse_1_1Tutorial_1_1LaunchDataScriptable" ],
        [ "CardDragTutorial", "classCardHouse_1_1Tutorial_1_1CardDragTutorial.html", "classCardHouse_1_1Tutorial_1_1CardDragTutorial" ],
        [ "GroupSetupTutorial", "classCardHouse_1_1Tutorial_1_1GroupSetupTutorial.html", "classCardHouse_1_1Tutorial_1_1GroupSetupTutorial" ],
        [ "ClosestCardHighlighter", "classCardHouse_1_1Tutorial_1_1ClosestCardHighlighter.html", null ],
        [ "StackTutorial", "classCardHouse_1_1Tutorial_1_1StackTutorial.html", "classCardHouse_1_1Tutorial_1_1StackTutorial" ],
        [ "SplayTutorial", "classCardHouse_1_1Tutorial_1_1SplayTutorial.html", "classCardHouse_1_1Tutorial_1_1SplayTutorial" ],
        [ "GridTutorial", "classCardHouse_1_1Tutorial_1_1GridTutorial.html", "classCardHouse_1_1Tutorial_1_1GridTutorial" ],
        [ "DiscardAllCardsOperator", "classCardHouse_1_1Tutorial_1_1DiscardAllCardsOperator.html", "classCardHouse_1_1Tutorial_1_1DiscardAllCardsOperator" ],
        [ "SpriteOperatorTutorial", "classCardHouse_1_1Tutorial_1_1SpriteOperatorTutorial.html", "classCardHouse_1_1Tutorial_1_1SpriteOperatorTutorial" ],
        [ "SpriteVoterTutorial", "classCardHouse_1_1Tutorial_1_1SpriteVoterTutorial.html", "classCardHouse_1_1Tutorial_1_1SpriteVoterTutorial" ],
        [ "TransferOperatorTutorialUI", "classCardHouse_1_1Tutorial_1_1TransferOperatorTutorialUI.html", "classCardHouse_1_1Tutorial_1_1TransferOperatorTutorialUI" ],
        [ "SeekerTutorial", "classCardHouse_1_1Tutorial_1_1SeekerTutorial.html", "classCardHouse_1_1Tutorial_1_1SeekerTutorial" ],
        [ "StringSeekerKVP", "classCardHouse_1_1Tutorial_1_1StringSeekerKVP.html", "classCardHouse_1_1Tutorial_1_1StringSeekerKVP" ],
        [ "EventChainsTutorial", "classCardHouse_1_1Tutorial_1_1EventChainsTutorial.html", "classCardHouse_1_1Tutorial_1_1EventChainsTutorial" ],
        [ "ValidDragTutorial", "classCardHouse_1_1Tutorial_1_1ValidDragTutorial.html", "classCardHouse_1_1Tutorial_1_1ValidDragTutorial" ],
        [ "MatureCropDragGate", "classCardHouse_1_1Tutorial_1_1MatureCropDragGate.html", "classCardHouse_1_1Tutorial_1_1MatureCropDragGate" ],
        [ "PhaseLabelUpdater", "classCardHouse_1_1Tutorial_1_1PhaseLabelUpdater.html", "classCardHouse_1_1Tutorial_1_1PhaseLabelUpdater" ],
        [ "Plant", "classCardHouse_1_1Tutorial_1_1Plant.html", "classCardHouse_1_1Tutorial_1_1Plant" ],
        [ "PlantGrowthScriptable", "classCardHouse_1_1Tutorial_1_1PlantGrowthScriptable.html", "classCardHouse_1_1Tutorial_1_1PlantGrowthScriptable" ],
        [ "PlantMaturityInfo", "classCardHouse_1_1Tutorial_1_1PlantMaturityInfo.html", "classCardHouse_1_1Tutorial_1_1PlantMaturityInfo" ],
        [ "WaterPlantAction", "classCardHouse_1_1Tutorial_1_1WaterPlantAction.html", "classCardHouse_1_1Tutorial_1_1WaterPlantAction" ],
        [ "WaterTargetPlantGate", "classCardHouse_1_1Tutorial_1_1WaterTargetPlantGate.html", "classCardHouse_1_1Tutorial_1_1WaterTargetPlantGate" ],
        [ "PresentationPointTutorial", "classCardHouse_1_1Tutorial_1_1PresentationPointTutorial.html", "classCardHouse_1_1Tutorial_1_1PresentationPointTutorial" ],
        [ "MultiBoardTutorial", "classCardHouse_1_1Tutorial_1_1MultiBoardTutorial.html", "classCardHouse_1_1Tutorial_1_1MultiBoardTutorial" ],
        [ "OutLinks", "classCardHouse_1_1Tutorial_1_1OutLinks.html", "classCardHouse_1_1Tutorial_1_1OutLinks" ],
        [ "SandboxManager", "classCardHouse_1_1Tutorial_1_1SandboxManager.html", "classCardHouse_1_1Tutorial_1_1SandboxManager" ],
        [ "SceneKeeper", "classCardHouse_1_1Tutorial_1_1SceneKeeper.html", null ],
        [ "SceneSpawner", "classCardHouse_1_1Tutorial_1_1SceneSpawner.html", "classCardHouse_1_1Tutorial_1_1SceneSpawner" ],
        [ "TutorialButton", "classCardHouse_1_1Tutorial_1_1TutorialButton.html", "classCardHouse_1_1Tutorial_1_1TutorialButton" ],
        [ "StringListScriptable", "classCardHouse_1_1Tutorial_1_1StringListScriptable.html", "classCardHouse_1_1Tutorial_1_1StringListScriptable" ]
      ] ],
      [ "PokerCardDefinition", "classCardHouse_1_1PokerCardDefinition.html", "classCardHouse_1_1PokerCardDefinition" ],
      [ "PokerCard", "classCardHouse_1_1PokerCard.html", "classCardHouse_1_1PokerCard" ],
      [ "ArcanaData", "classCardHouse_1_1ArcanaData.html", "classCardHouse_1_1ArcanaData" ],
      [ "TarotCard", "classCardHouse_1_1TarotCard.html", "classCardHouse_1_1TarotCard" ],
      [ "TarotCardDefinition", "classCardHouse_1_1TarotCardDefinition.html", "classCardHouse_1_1TarotCardDefinition" ],
      [ "Card", "classCardHouse_1_1Card.html", "classCardHouse_1_1Card" ],
      [ "Activatable", "classCardHouse_1_1Activatable.html", "classCardHouse_1_1Activatable" ],
      [ "CardTargetCardOperator", "classCardHouse_1_1CardTargetCardOperator.html", "classCardHouse_1_1CardTargetCardOperator" ],
      [ "CardTransferOperator", "classCardHouse_1_1CardTransferOperator.html", "classCardHouse_1_1CardTransferOperator" ],
      [ "DiscardCardOperator", "classCardHouse_1_1DiscardCardOperator.html", "classCardHouse_1_1DiscardCardOperator" ],
      [ "DiscardTargetCardOperator", "classCardHouse_1_1DiscardTargetCardOperator.html", "classCardHouse_1_1DiscardTargetCardOperator" ],
      [ "ShuffleOperator", "classCardHouse_1_1ShuffleOperator.html", "classCardHouse_1_1ShuffleOperator" ],
      [ "CardDefinition", "classCardHouse_1_1CardDefinition.html", "classCardHouse_1_1CardDefinition" ],
      [ "DeckDefinition", "classCardHouse_1_1DeckDefinition.html", "classCardHouse_1_1DeckDefinition" ],
      [ "ClickDetector", "classCardHouse_1_1ClickDetector.html", "classCardHouse_1_1ClickDetector" ],
      [ "PhaseGateClick", "classCardHouse_1_1PhaseGateClick.html", "classCardHouse_1_1PhaseGateClick" ],
      [ "GroupConditional", "classCardHouse_1_1GroupConditional.html", "classCardHouse_1_1GroupConditional" ],
      [ "GroupNameUnityActionKvp", "classCardHouse_1_1GroupNameUnityActionKvp.html", "classCardHouse_1_1GroupNameUnityActionKvp" ],
      [ "PhaseConditional", "classCardHouse_1_1PhaseConditional.html", "classCardHouse_1_1PhaseConditional" ],
      [ "StringUnityActionKvp", "classCardHouse_1_1StringUnityActionKvp.html", "classCardHouse_1_1StringUnityActionKvp" ],
      [ "CurrencyChangeDetector", "classCardHouse_1_1CurrencyChangeDetector.html", "classCardHouse_1_1CurrencyChangeDetector" ],
      [ "CurrencyContainer", "classCardHouse_1_1CurrencyContainer.html", "classCardHouse_1_1CurrencyContainer" ],
      [ "CurrencyCost", "classCardHouse_1_1CurrencyCost.html", "classCardHouse_1_1CurrencyCost" ],
      [ "CurrencyQuantity", "classCardHouse_1_1CurrencyQuantity.html", "classCardHouse_1_1CurrencyQuantity" ],
      [ "CurrencyRegistry", "classCardHouse_1_1CurrencyRegistry.html", "classCardHouse_1_1CurrencyRegistry" ],
      [ "CurrencyScriptable", "classCardHouse_1_1CurrencyScriptable.html", "classCardHouse_1_1CurrencyScriptable" ],
      [ "CurrencyUI", "classCardHouse_1_1CurrencyUI.html", "classCardHouse_1_1CurrencyUI" ],
      [ "CurrencyWallet", "classCardHouse_1_1CurrencyWallet.html", "classCardHouse_1_1CurrencyWallet" ],
      [ "CurrencyOperator", "classCardHouse_1_1CurrencyOperator.html", "classCardHouse_1_1CurrencyOperator" ],
      [ "CurrencyRefillOperator", "classCardHouse_1_1CurrencyRefillOperator.html", "classCardHouse_1_1CurrencyRefillOperator" ],
      [ "IncrementCurrencyOperator", "classCardHouse_1_1IncrementCurrencyOperator.html", "classCardHouse_1_1IncrementCurrencyOperator" ],
      [ "DragDetector", "classCardHouse_1_1DragDetector.html", "classCardHouse_1_1DragDetector" ],
      [ "Dragging", "classCardHouse_1_1Dragging.html", "classCardHouse_1_1Dragging" ],
      [ "DragOperator", "classCardHouse_1_1DragOperator.html", "classCardHouse_1_1DragOperator" ],
      [ "EventChain", "classCardHouse_1_1EventChain.html", "classCardHouse_1_1EventChain" ],
      [ "TimedEvent", "classCardHouse_1_1TimedEvent.html", "classCardHouse_1_1TimedEvent" ],
      [ "BlockAllDrops", "classCardHouse_1_1BlockAllDrops.html", "classCardHouse_1_1BlockAllDrops" ],
      [ "CurrencyGate", "classCardHouse_1_1CurrencyGate.html", "classCardHouse_1_1CurrencyGate" ],
      [ "Gate", "classCardHouse_1_1Gate.html", "classCardHouse_1_1Gate" ],
      [ "GateCollection", "classCardHouse_1_1GateCollection.html", "classCardHouse_1_1GateCollection" ],
      [ "DropParams", "classCardHouse_1_1DropParams.html", "classCardHouse_1_1DropParams" ],
      [ "NoParams", "classCardHouse_1_1NoParams.html", null ],
      [ "TargetCardParams", "classCardHouse_1_1TargetCardParams.html", "classCardHouse_1_1TargetCardParams" ],
      [ "CardGroup", "classCardHouse_1_1CardGroup.html", "classCardHouse_1_1CardGroup" ],
      [ "GroupRegistry", "classCardHouse_1_1GroupRegistry.html", "classCardHouse_1_1GroupRegistry" ],
      [ "CardGridLayout", "classCardHouse_1_1CardGridLayout.html", "classCardHouse_1_1CardGridLayout" ],
      [ "CardGroupSettings", "classCardHouse_1_1CardGroupSettings.html", "classCardHouse_1_1CardGroupSettings" ],
      [ "SlotLayout", "classCardHouse_1_1SlotLayout.html", "classCardHouse_1_1SlotLayout" ],
      [ "SplayLayout", "classCardHouse_1_1SplayLayout.html", "classCardHouse_1_1SplayLayout" ],
      [ "StackLayout", "classCardHouse_1_1StackLayout.html", "classCardHouse_1_1StackLayout" ],
      [ "MountDetector", "classCardHouse_1_1MountDetector.html", "classCardHouse_1_1MountDetector" ],
      [ "DragTransition", "classCardHouse_1_1DragTransition.html", "classCardHouse_1_1DragTransition" ],
      [ "GroupTransition", "classCardHouse_1_1GroupTransition.html", "classCardHouse_1_1GroupTransition" ],
      [ "HoverDetector", "classCardHouse_1_1HoverDetector.html", "classCardHouse_1_1HoverDetector" ],
      [ "TriggerEnterRelay", "classCardHouse_1_1TriggerEnterRelay.html", "classCardHouse_1_1TriggerEnterRelay" ],
      [ "LifetimeDestructor", "classCardHouse_1_1LifetimeDestructor.html", "classCardHouse_1_1LifetimeDestructor" ],
      [ "CardDropGateDimmer", "classCardHouse_1_1CardDropGateDimmer.html", "classCardHouse_1_1CardDropGateDimmer" ],
      [ "CardLoyalty", "classCardHouse_1_1CardLoyalty.html", "classCardHouse_1_1CardLoyalty" ],
      [ "DragGateDimmer", "classCardHouse_1_1DragGateDimmer.html", "classCardHouse_1_1DragGateDimmer" ],
      [ "GroupDropGateDimmer", "classCardHouse_1_1GroupDropGateDimmer.html", "classCardHouse_1_1GroupDropGateDimmer" ],
      [ "LoyaltyGateCardDrop", "classCardHouse_1_1LoyaltyGateCardDrop.html", "classCardHouse_1_1LoyaltyGateCardDrop" ],
      [ "Phase", "classCardHouse_1_1Phase.html", "classCardHouse_1_1Phase" ],
      [ "PhaseChangeDetector", "classCardHouse_1_1PhaseChangeDetector.html", "classCardHouse_1_1PhaseChangeDetector" ],
      [ "PhaseGateCardDragStart", "classCardHouse_1_1PhaseGateCardDragStart.html", "classCardHouse_1_1PhaseGateCardDragStart" ],
      [ "PhaseGateCardDrop", "classCardHouse_1_1PhaseGateCardDrop.html", "classCardHouse_1_1PhaseGateCardDrop" ],
      [ "PhaseManager", "classCardHouse_1_1PhaseManager.html", "classCardHouse_1_1PhaseManager" ],
      [ "BaseSeekerComponent", "classCardHouse_1_1BaseSeekerComponent.html", "classCardHouse_1_1BaseSeekerComponent" ],
      [ "Homing", "classCardHouse_1_1Homing.html", "classCardHouse_1_1Homing" ],
      [ "Scaling", "classCardHouse_1_1Scaling.html", "classCardHouse_1_1Scaling" ],
      [ "Turning", "classCardHouse_1_1Turning.html", "classCardHouse_1_1Turning" ],
      [ "AnimCurveFloatSeeker", "classCardHouse_1_1AnimCurveFloatSeeker.html", "classCardHouse_1_1AnimCurveFloatSeeker" ],
      [ "AnimCurveFloatSeekerScriptable", "classCardHouse_1_1AnimCurveFloatSeekerScriptable.html", "classCardHouse_1_1AnimCurveFloatSeekerScriptable" ],
      [ "ExponentialAngleFloatSeeker", "classCardHouse_1_1ExponentialAngleFloatSeeker.html", "classCardHouse_1_1ExponentialAngleFloatSeeker" ],
      [ "ExponentialAngleFloatSeekerScriptable", "classCardHouse_1_1ExponentialAngleFloatSeekerScriptable.html", "classCardHouse_1_1ExponentialAngleFloatSeekerScriptable" ],
      [ "ExponentialFloatSeeker", "classCardHouse_1_1ExponentialFloatSeeker.html", "classCardHouse_1_1ExponentialFloatSeeker" ],
      [ "ExponentialFloatSeekerScriptable", "classCardHouse_1_1ExponentialFloatSeekerScriptable.html", "classCardHouse_1_1ExponentialFloatSeekerScriptable" ],
      [ "InstantFloatSeeker", "classCardHouse_1_1InstantFloatSeeker.html", "classCardHouse_1_1InstantFloatSeeker" ],
      [ "WaypointCurveFloatAngleSeeker", "classCardHouse_1_1WaypointCurveFloatAngleSeeker.html", "classCardHouse_1_1WaypointCurveFloatAngleSeeker" ],
      [ "WaypointCurveFloatAngleSeekerScriptable", "classCardHouse_1_1WaypointCurveFloatAngleSeekerScriptable.html", "classCardHouse_1_1WaypointCurveFloatAngleSeekerScriptable" ],
      [ "WaypointCurveFloatSeeker", "classCardHouse_1_1WaypointCurveFloatSeeker.html", "classCardHouse_1_1WaypointCurveFloatSeeker" ],
      [ "WaypointCurveFloatSeekerScriptable", "classCardHouse_1_1WaypointCurveFloatSeekerScriptable.html", "classCardHouse_1_1WaypointCurveFloatSeekerScriptable" ],
      [ "Seeker", "classCardHouse_1_1Seeker.html", "classCardHouse_1_1Seeker" ],
      [ "SeekerScriptable", "classCardHouse_1_1SeekerScriptable.html", "classCardHouse_1_1SeekerScriptable" ],
      [ "SeekerScriptableSet", "classCardHouse_1_1SeekerScriptableSet.html", "classCardHouse_1_1SeekerScriptableSet" ],
      [ "SeekerSet", "classCardHouse_1_1SeekerSet.html", "classCardHouse_1_1SeekerSet" ],
      [ "SeekerSetList", "classCardHouse_1_1SeekerSetList.html", "classCardHouse_1_1SeekerSetList" ],
      [ "AnimCurveVector3Seeker", "classCardHouse_1_1AnimCurveVector3Seeker.html", "classCardHouse_1_1AnimCurveVector3Seeker" ],
      [ "AnimCurveVector3SeekerScriptable", "classCardHouse_1_1AnimCurveVector3SeekerScriptable.html", "classCardHouse_1_1AnimCurveVector3SeekerScriptable" ],
      [ "ContinuousInstantVector3Seeker", "classCardHouse_1_1ContinuousInstantVector3Seeker.html", "classCardHouse_1_1ContinuousInstantVector3Seeker" ],
      [ "ContinuousInstantVector3SeekerScriptable", "classCardHouse_1_1ContinuousInstantVector3SeekerScriptable.html", "classCardHouse_1_1ContinuousInstantVector3SeekerScriptable" ],
      [ "ExponentialVector3Seeker", "classCardHouse_1_1ExponentialVector3Seeker.html", "classCardHouse_1_1ExponentialVector3Seeker" ],
      [ "ExponentialVector3SeekerScriptable", "classCardHouse_1_1ExponentialVector3SeekerScriptable.html", "classCardHouse_1_1ExponentialVector3SeekerScriptable" ],
      [ "InstantVector3Seeker", "classCardHouse_1_1InstantVector3Seeker.html", "classCardHouse_1_1InstantVector3Seeker" ],
      [ "RandomizedCurveVector3SeekerScriptable", "classCardHouse_1_1RandomizedCurveVector3SeekerScriptable.html", "classCardHouse_1_1RandomizedCurveVector3SeekerScriptable" ],
      [ "TweakVector3Seeker", "classCardHouse_1_1TweakVector3Seeker.html", "classCardHouse_1_1TweakVector3Seeker" ],
      [ "TweakVector3SeekerScriptable", "classCardHouse_1_1TweakVector3SeekerScriptable.html", "classCardHouse_1_1TweakVector3SeekerScriptable" ],
      [ "WaypointCurveVector3Seeker", "classCardHouse_1_1WaypointCurveVector3Seeker.html", "classCardHouse_1_1WaypointCurveVector3Seeker" ],
      [ "WaypointCurveVector3SeekerScriptable", "classCardHouse_1_1WaypointCurveVector3SeekerScriptable.html", "classCardHouse_1_1WaypointCurveVector3SeekerScriptable" ],
      [ "CardSetup", "classCardHouse_1_1CardSetup.html", "classCardHouse_1_1CardSetup" ],
      [ "DeckSetup", "classCardHouse_1_1DeckSetup.html", "classCardHouse_1_1DeckSetup" ],
      [ "GroupSetup", "classCardHouse_1_1GroupSetup.html", "classCardHouse_1_1GroupSetup" ],
      [ "MultiplayerBoardSetup", "classCardHouse_1_1MultiplayerBoardSetup.html", "classCardHouse_1_1MultiplayerBoardSetup" ],
      [ "MultiSpriteOperator", "classCardHouse_1_1MultiSpriteOperator.html", "classCardHouse_1_1MultiSpriteOperator" ],
      [ "SpriteColorOperator", "classCardHouse_1_1SpriteColorOperator.html", "classCardHouse_1_1SpriteColorOperator" ],
      [ "SpriteImageOperator", "classCardHouse_1_1SpriteImageOperator.html", "classCardHouse_1_1SpriteImageOperator" ],
      [ "SpriteOperator", "classCardHouse_1_1SpriteOperator.html", "classCardHouse_1_1SpriteOperator" ],
      [ "Toggleable", "classCardHouse_1_1Toggleable.html", "classCardHouse_1_1Toggleable" ]
    ] ],
    [ "FreeformTarotManager", "classFreeformTarotManager.html", "classFreeformTarotManager" ],
    [ "SceneChanger", "classSceneChanger.html", "classSceneChanger" ]
];