var annotated_dup =
[
    [ "CardHouse", "namespaceCardHouse.html", [
      [ "SampleGames", "namespaceCardHouse_1_1SampleGames.html", [
        [ "DeckBuilder", "namespaceCardHouse_1_1SampleGames_1_1DeckBuilder.html", [
          [ "DamageGroupOperator", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageGroupOperator.html", null ],
          [ "DamageTargetOperator", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1DamageTargetOperator.html", null ],
          [ "Health", "classCardHouse_1_1SampleGames_1_1DeckBuilder_1_1Health.html", null ]
        ] ],
        [ "MemoryMatch", "namespaceCardHouse_1_1SampleGames_1_1MemoryMatch.html", [
          [ "MemoryCard", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryCard.html", null ],
          [ "MemoryGame", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryGame.html", null ],
          [ "MemoryUI", "classCardHouse_1_1SampleGames_1_1MemoryMatch_1_1MemoryUI.html", null ]
        ] ],
        [ "Solitaire", "namespaceCardHouse_1_1SampleGames_1_1Solitaire.html", [
          [ "SolitaireCardDragHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireCardDragHandler.html", null ],
          [ "SolitaireColumnChangeHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnChangeHandler.html", null ],
          [ "SolitaireColumnDropGate", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireColumnDropGate.html", null ],
          [ "SolitaireDeckClickHandler", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireDeckClickHandler.html", null ],
          [ "SolitaireScorePileDropGate", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireScorePileDropGate.html", null ],
          [ "SolitaireSetup", "classCardHouse_1_1SampleGames_1_1Solitaire_1_1SolitaireSetup.html", null ]
        ] ],
        [ "Tarot", "namespaceCardHouse_1_1SampleGames_1_1Tarot.html", [
          [ "SpreadManager", "classCardHouse_1_1SampleGames_1_1Tarot_1_1SpreadManager.html", null ],
          [ "TarotSpread", "classCardHouse_1_1SampleGames_1_1Tarot_1_1TarotSpread.html", null ]
        ] ]
      ] ],
      [ "TestScenes", "namespaceCardHouse_1_1TestScenes.html", [
        [ "WaypointTesterCard", "classCardHouse_1_1TestScenes_1_1WaypointTesterCard.html", null ],
        [ "WaypointTesterGroup", "classCardHouse_1_1TestScenes_1_1WaypointTesterGroup.html", null ]
      ] ],
      [ "Tutorial", "namespaceCardHouse_1_1Tutorial.html", [
        [ "CardDragTutorial", "classCardHouse_1_1Tutorial_1_1CardDragTutorial.html", null ],
        [ "ClosestCardHighlighter", "classCardHouse_1_1Tutorial_1_1ClosestCardHighlighter.html", null ],
        [ "DiscardAllCardsOperator", "classCardHouse_1_1Tutorial_1_1DiscardAllCardsOperator.html", null ],
        [ "EventChainsTutorial", "classCardHouse_1_1Tutorial_1_1EventChainsTutorial.html", null ],
        [ "GridTutorial", "classCardHouse_1_1Tutorial_1_1GridTutorial.html", null ],
        [ "GroupSetupTutorial", "classCardHouse_1_1Tutorial_1_1GroupSetupTutorial.html", null ],
        [ "LaunchDataScriptable", "classCardHouse_1_1Tutorial_1_1LaunchDataScriptable.html", null ],
        [ "MatureCropDragGate", "classCardHouse_1_1Tutorial_1_1MatureCropDragGate.html", null ],
        [ "MultiBoardTutorial", "classCardHouse_1_1Tutorial_1_1MultiBoardTutorial.html", "classCardHouse_1_1Tutorial_1_1MultiBoardTutorial" ],
        [ "OutLinks", "classCardHouse_1_1Tutorial_1_1OutLinks.html", null ],
        [ "PhaseLabelUpdater", "classCardHouse_1_1Tutorial_1_1PhaseLabelUpdater.html", null ],
        [ "Plant", "classCardHouse_1_1Tutorial_1_1Plant.html", null ],
        [ "PlantGrowthScriptable", "classCardHouse_1_1Tutorial_1_1PlantGrowthScriptable.html", null ],
        [ "PlantMaturityInfo", "classCardHouse_1_1Tutorial_1_1PlantMaturityInfo.html", null ],
        [ "PresentationPointTutorial", "classCardHouse_1_1Tutorial_1_1PresentationPointTutorial.html", null ],
        [ "SandboxManager", "classCardHouse_1_1Tutorial_1_1SandboxManager.html", null ],
        [ "SceneKeeper", "classCardHouse_1_1Tutorial_1_1SceneKeeper.html", null ],
        [ "SceneSpawner", "classCardHouse_1_1Tutorial_1_1SceneSpawner.html", null ],
        [ "SeekerTutorial", "classCardHouse_1_1Tutorial_1_1SeekerTutorial.html", null ],
        [ "SplayTutorial", "classCardHouse_1_1Tutorial_1_1SplayTutorial.html", null ],
        [ "SpriteOperatorTutorial", "classCardHouse_1_1Tutorial_1_1SpriteOperatorTutorial.html", null ],
        [ "SpriteVoterTutorial", "classCardHouse_1_1Tutorial_1_1SpriteVoterTutorial.html", null ],
        [ "StackTutorial", "classCardHouse_1_1Tutorial_1_1StackTutorial.html", null ],
        [ "StringListScriptable", "classCardHouse_1_1Tutorial_1_1StringListScriptable.html", null ],
        [ "StringSeekerKVP", "classCardHouse_1_1Tutorial_1_1StringSeekerKVP.html", null ],
        [ "TransferOperatorTutorialUI", "classCardHouse_1_1Tutorial_1_1TransferOperatorTutorialUI.html", null ],
        [ "TutorialButton", "classCardHouse_1_1Tutorial_1_1TutorialButton.html", null ],
        [ "ValidDragTutorial", "classCardHouse_1_1Tutorial_1_1ValidDragTutorial.html", null ],
        [ "WaterPlantAction", "classCardHouse_1_1Tutorial_1_1WaterPlantAction.html", null ],
        [ "WaterTargetPlantGate", "classCardHouse_1_1Tutorial_1_1WaterTargetPlantGate.html", null ]
      ] ],
      [ "Activatable", "classCardHouse_1_1Activatable.html", null ],
      [ "AnimCurveFloatSeeker", "classCardHouse_1_1AnimCurveFloatSeeker.html", null ],
      [ "AnimCurveFloatSeekerScriptable", "classCardHouse_1_1AnimCurveFloatSeekerScriptable.html", null ],
      [ "AnimCurveVector3Seeker", "classCardHouse_1_1AnimCurveVector3Seeker.html", null ],
      [ "AnimCurveVector3SeekerScriptable", "classCardHouse_1_1AnimCurveVector3SeekerScriptable.html", null ],
      [ "ArcanaData", "classCardHouse_1_1ArcanaData.html", null ],
      [ "BaseSeekerComponent", "classCardHouse_1_1BaseSeekerComponent.html", null ],
      [ "BlockAllDrops", "classCardHouse_1_1BlockAllDrops.html", null ],
      [ "Card", "classCardHouse_1_1Card.html", "classCardHouse_1_1Card" ],
      [ "CardDefinition", "classCardHouse_1_1CardDefinition.html", null ],
      [ "CardDropGateDimmer", "classCardHouse_1_1CardDropGateDimmer.html", null ],
      [ "CardGridLayout", "classCardHouse_1_1CardGridLayout.html", null ],
      [ "CardGroup", "classCardHouse_1_1CardGroup.html", null ],
      [ "CardGroupSettings", "classCardHouse_1_1CardGroupSettings.html", null ],
      [ "CardLoyalty", "classCardHouse_1_1CardLoyalty.html", null ],
      [ "CardSetup", "classCardHouse_1_1CardSetup.html", null ],
      [ "CardTargetCardOperator", "classCardHouse_1_1CardTargetCardOperator.html", null ],
      [ "CardTransferOperator", "classCardHouse_1_1CardTransferOperator.html", null ],
      [ "ClickDetector", "classCardHouse_1_1ClickDetector.html", null ],
      [ "ContinuousInstantVector3Seeker", "classCardHouse_1_1ContinuousInstantVector3Seeker.html", null ],
      [ "ContinuousInstantVector3SeekerScriptable", "classCardHouse_1_1ContinuousInstantVector3SeekerScriptable.html", null ],
      [ "CurrencyChangeDetector", "classCardHouse_1_1CurrencyChangeDetector.html", null ],
      [ "CurrencyContainer", "classCardHouse_1_1CurrencyContainer.html", null ],
      [ "CurrencyCost", "classCardHouse_1_1CurrencyCost.html", "classCardHouse_1_1CurrencyCost" ],
      [ "CurrencyGate", "classCardHouse_1_1CurrencyGate.html", null ],
      [ "CurrencyOperator", "classCardHouse_1_1CurrencyOperator.html", null ],
      [ "CurrencyQuantity", "classCardHouse_1_1CurrencyQuantity.html", null ],
      [ "CurrencyRefillOperator", "classCardHouse_1_1CurrencyRefillOperator.html", null ],
      [ "CurrencyRegistry", "classCardHouse_1_1CurrencyRegistry.html", null ],
      [ "CurrencyScriptable", "classCardHouse_1_1CurrencyScriptable.html", null ],
      [ "CurrencyUI", "classCardHouse_1_1CurrencyUI.html", null ],
      [ "CurrencyWallet", "classCardHouse_1_1CurrencyWallet.html", null ],
      [ "DeckDefinition", "classCardHouse_1_1DeckDefinition.html", null ],
      [ "DeckSetup", "classCardHouse_1_1DeckSetup.html", null ],
      [ "DiscardCardOperator", "classCardHouse_1_1DiscardCardOperator.html", null ],
      [ "DiscardTargetCardOperator", "classCardHouse_1_1DiscardTargetCardOperator.html", null ],
      [ "DragDetector", "classCardHouse_1_1DragDetector.html", null ],
      [ "DragGateDimmer", "classCardHouse_1_1DragGateDimmer.html", null ],
      [ "Dragging", "classCardHouse_1_1Dragging.html", null ],
      [ "DragOperator", "classCardHouse_1_1DragOperator.html", null ],
      [ "DragTransition", "classCardHouse_1_1DragTransition.html", null ],
      [ "DropParams", "classCardHouse_1_1DropParams.html", null ],
      [ "EventChain", "classCardHouse_1_1EventChain.html", null ],
      [ "ExponentialAngleFloatSeeker", "classCardHouse_1_1ExponentialAngleFloatSeeker.html", null ],
      [ "ExponentialAngleFloatSeekerScriptable", "classCardHouse_1_1ExponentialAngleFloatSeekerScriptable.html", null ],
      [ "ExponentialFloatSeeker", "classCardHouse_1_1ExponentialFloatSeeker.html", null ],
      [ "ExponentialFloatSeekerScriptable", "classCardHouse_1_1ExponentialFloatSeekerScriptable.html", null ],
      [ "ExponentialVector3Seeker", "classCardHouse_1_1ExponentialVector3Seeker.html", null ],
      [ "ExponentialVector3SeekerScriptable", "classCardHouse_1_1ExponentialVector3SeekerScriptable.html", null ],
      [ "Gate", "classCardHouse_1_1Gate.html", null ],
      [ "GateCollection", "classCardHouse_1_1GateCollection.html", null ],
      [ "GroupConditional", "classCardHouse_1_1GroupConditional.html", null ],
      [ "GroupDropGateDimmer", "classCardHouse_1_1GroupDropGateDimmer.html", null ],
      [ "GroupNameUnityActionKvp", "classCardHouse_1_1GroupNameUnityActionKvp.html", null ],
      [ "GroupRegistry", "classCardHouse_1_1GroupRegistry.html", "classCardHouse_1_1GroupRegistry" ],
      [ "GroupSetup", "classCardHouse_1_1GroupSetup.html", "classCardHouse_1_1GroupSetup" ],
      [ "GroupTransition", "classCardHouse_1_1GroupTransition.html", null ],
      [ "Homing", "classCardHouse_1_1Homing.html", null ],
      [ "HoverDetector", "classCardHouse_1_1HoverDetector.html", null ],
      [ "IncrementCurrencyOperator", "classCardHouse_1_1IncrementCurrencyOperator.html", null ],
      [ "InstantFloatSeeker", "classCardHouse_1_1InstantFloatSeeker.html", null ],
      [ "InstantVector3Seeker", "classCardHouse_1_1InstantVector3Seeker.html", null ],
      [ "LifetimeDestructor", "classCardHouse_1_1LifetimeDestructor.html", null ],
      [ "LoyaltyGateCardDrop", "classCardHouse_1_1LoyaltyGateCardDrop.html", null ],
      [ "MountDetector", "classCardHouse_1_1MountDetector.html", null ],
      [ "MultiplayerBoardSetup", "classCardHouse_1_1MultiplayerBoardSetup.html", "classCardHouse_1_1MultiplayerBoardSetup" ],
      [ "MultiSpriteOperator", "classCardHouse_1_1MultiSpriteOperator.html", null ],
      [ "NoParams", "classCardHouse_1_1NoParams.html", null ],
      [ "Phase", "classCardHouse_1_1Phase.html", null ],
      [ "PhaseChangeDetector", "classCardHouse_1_1PhaseChangeDetector.html", null ],
      [ "PhaseConditional", "classCardHouse_1_1PhaseConditional.html", null ],
      [ "PhaseGateCardDragStart", "classCardHouse_1_1PhaseGateCardDragStart.html", null ],
      [ "PhaseGateCardDrop", "classCardHouse_1_1PhaseGateCardDrop.html", null ],
      [ "PhaseGateClick", "classCardHouse_1_1PhaseGateClick.html", null ],
      [ "PhaseManager", "classCardHouse_1_1PhaseManager.html", null ],
      [ "PokerCard", "classCardHouse_1_1PokerCard.html", null ],
      [ "PokerCardDefinition", "classCardHouse_1_1PokerCardDefinition.html", null ],
      [ "RandomizedCurveVector3SeekerScriptable", "classCardHouse_1_1RandomizedCurveVector3SeekerScriptable.html", null ],
      [ "Scaling", "classCardHouse_1_1Scaling.html", null ],
      [ "Seeker", "classCardHouse_1_1Seeker.html", null ],
      [ "SeekerScriptable", "classCardHouse_1_1SeekerScriptable.html", null ],
      [ "SeekerScriptableSet", "classCardHouse_1_1SeekerScriptableSet.html", null ],
      [ "SeekerSet", "classCardHouse_1_1SeekerSet.html", null ],
      [ "SeekerSetList", "classCardHouse_1_1SeekerSetList.html", null ],
      [ "ShuffleOperator", "classCardHouse_1_1ShuffleOperator.html", null ],
      [ "SlotLayout", "classCardHouse_1_1SlotLayout.html", null ],
      [ "SplayLayout", "classCardHouse_1_1SplayLayout.html", null ],
      [ "SpriteColorOperator", "classCardHouse_1_1SpriteColorOperator.html", "classCardHouse_1_1SpriteColorOperator" ],
      [ "SpriteImageOperator", "classCardHouse_1_1SpriteImageOperator.html", "classCardHouse_1_1SpriteImageOperator" ],
      [ "SpriteOperator", "classCardHouse_1_1SpriteOperator.html", null ],
      [ "StackLayout", "classCardHouse_1_1StackLayout.html", null ],
      [ "StringUnityActionKvp", "classCardHouse_1_1StringUnityActionKvp.html", null ],
      [ "TargetCardParams", "classCardHouse_1_1TargetCardParams.html", null ],
      [ "TarotCard", "classCardHouse_1_1TarotCard.html", null ],
      [ "TarotCardDefinition", "classCardHouse_1_1TarotCardDefinition.html", null ],
      [ "TimedEvent", "classCardHouse_1_1TimedEvent.html", null ],
      [ "Toggleable", "classCardHouse_1_1Toggleable.html", null ],
      [ "TriggerEnterRelay", "classCardHouse_1_1TriggerEnterRelay.html", null ],
      [ "Turning", "classCardHouse_1_1Turning.html", null ],
      [ "TweakVector3Seeker", "classCardHouse_1_1TweakVector3Seeker.html", null ],
      [ "TweakVector3SeekerScriptable", "classCardHouse_1_1TweakVector3SeekerScriptable.html", null ],
      [ "WaypointCurveFloatAngleSeeker", "classCardHouse_1_1WaypointCurveFloatAngleSeeker.html", null ],
      [ "WaypointCurveFloatAngleSeekerScriptable", "classCardHouse_1_1WaypointCurveFloatAngleSeekerScriptable.html", null ],
      [ "WaypointCurveFloatSeeker", "classCardHouse_1_1WaypointCurveFloatSeeker.html", null ],
      [ "WaypointCurveFloatSeekerScriptable", "classCardHouse_1_1WaypointCurveFloatSeekerScriptable.html", null ],
      [ "WaypointCurveVector3Seeker", "classCardHouse_1_1WaypointCurveVector3Seeker.html", null ],
      [ "WaypointCurveVector3SeekerScriptable", "classCardHouse_1_1WaypointCurveVector3SeekerScriptable.html", null ]
    ] ],
    [ "FreeformTarotManager", "classFreeformTarotManager.html", null ],
    [ "SceneChanger", "classSceneChanger.html", null ]
];